[package]
name = "ghostcheck-frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
console_log = "1.0.0"
leptos = { version = "0.8.15", features = ["csr"] }
leptos_meta = "0.8.5"
leptos_router = "0.8.11"
log = "0.4.29"
